### ISSUE TITLE
Improve first benchmark

### ISSUE THREAD

**Issue by ekrebs5** [ekrebs5/hyrise#3]
- [ ] use tcp-h tables (and know exactly which, the size and the column / group by values)
- [ ] look at tcp queries and make a sensible query

**Comment by ekrebs5** [comment]
[schema](https://docs.snowflake.net/manuals/user-guide/sample-data-tpch.html)

Example aggregates:
- on l_returnflag, l_linestatus
- on l_orderkey, o_orderdata, o_shippriority
- on n_name
- (on supp_nation, cust_nation, l_year)
- on o_year
- on c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment (join customer and orders and nations)
- on p_brand, p_type, p_size
- on c_name, c_custkey, o_orderdate, o_orderkey, o_totalprice (join customer and orders)
- on s_name

**Comment by ekrebs5** [comment]
there is a tcp generator: src/benchmarklib/tcph/tcph_db_generator.cpp/.hpp

**Comment by aloeser** [comment]
2018-12-11 10:33:39
Running ./cmake-build-release/hyriseMicroBenchmarks
Run on (8 X 2401 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 6144K (x1)
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
[PERF] operator[] used at src/lib/storage/reference_segment.cpp:31
	Performance can be affected. This warning is only shown once.

[PERF] operator[] used at src/lib/storage/value_segment.cpp:54
	Performance can be affected. This warning is only shown once.

[PERF] operator[] used at src/lib/storage/value_segment.cpp:54
	Performance can be affected. This warning is only shown once.

-----------------------------------------------------------------------------------------
Benchmark                                                  Time           CPU Iterations
-----------------------------------------------------------------------------------------
MicroBenchmarkBasicFixture/BM_Aggregate_1_Column        9632 ns       9636 ns      72223
MicroBenchmarkBasicFixture/BM_Aggregate_2_Columns      13081 ns      13087 ns      52597
[PERF] No std::array implementation initialized - falling back to vector at src/lib/operators/aggregate.cpp:608
	Performance can be affected. This warning is only shown once.

MicroBenchmarkBasicFixture/BM_Aggregate_4_Columns      23365 ns      23374 ns      29191

**Comment by aloeser** [comment]
2018-12-11 18:59:15
Running ./cmake-build-release/hyriseMicroBenchmarks
Run on (8 X 2401 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 256K (x4)
  L3 Unified 6144K (x1)
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
Starting to generate TCPH tables with scale factor 1...  done
Starting to compute join query part for TPCH-18 (modified)...
[PERF] operator[] used at src/lib/storage/reference_segment.cpp:31
	Performance can be affected. This warning is only shown once.

[PERF] operator[] used at src/lib/storage/value_segment.cpp:54
	Performance can be affected. This warning is only shown once.

Finished to compute join query part for TPCH-18 (modified)
created table size is 559733
-----------------------------------------------------------------------------------------
Benchmark                                                  Time           CPU Iterations
-----------------------------------------------------------------------------------------
MicroBenchmarkBasicFixture/BM_Aggregate_1_Column    82581997 ns   82167037 ns          8
MicroBenchmarkBasicFixture/BM_Aggregate_2_Columns  160591602 ns  158487503 ns          4
[PERF] No std::array implementation initialized - falling back to vector at src/lib/operators/aggregate.cpp:608
	Performance can be affected. This warning is only shown once.

[PERF] operator[] used at src/lib/storage/value_segment.cpp:54
	Performance can be affected. This warning is only shown once.

MicroBenchmarkBasicFixture/BM_Aggregate_4_Columns  446739078 ns  446882757 ns          2
